# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_personnames"
description = "API for formatting person names according to language-dependent conventions"
version = "0.1.0"
license-file = "LICENSE"
publish = false # excluded from 1.3 release


authors.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
icu_locid = { workspace = true }

icu_provider = { workspace = true, features = ["macros", "serde"] }
icu_properties = { workspace = true, features = ["compiled_data"] }
zerovec = { workspace = true, features = ["serde", "derive"] }
databake = { workspace = true, features = ["derive"], optional = true }
icu_personnames_data = { workspace = true, optional = true }
icu_locid_transform = { workspace = true }

serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }
litemap = { workspace = true }
zerofrom = { workspace = true }
regex = "=1.8.4"
lazy_static = "1.4"

[features]
default = ["compiled_data"]
std = ["icu_locid/std", "icu_provider/std"]
serde = ["dep:serde", "zerovec/serde", "icu_provider/serde"]
datagen = ["serde", "std", "dep:databake", "zerovec/databake"]
compiled_data = ["dep:icu_personnames_data"]

[[test]]
name = "tests"
path = "tests/tests.rs"
